# Site settings
title: AlexTanJX.com
header-img: img/home-bg.jpg
email: publicmutual@alextanjx.com
description: "Full range of financial information including unit trust, private retirement scheme, KLCI and foreign shares."
baseurl: ""
url: "http://alextanjx.com"
twitter_username: SBootstrap

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
